spring:
  profiles:
    active: prod # Alterado para 'prod' para conectar no PostgreSQL

---
# ?? CONFIGURAÇÃO DE DESENVOLVIMENTO (Banco H2 em Memória)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:deliverydb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha

server:
  port: 8080

---
# ? CONFIGURAÇÃO DE PRODUÇÃO (Banco PostgreSQL)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db # Certifique-se de criar essa database vazia no PostgreSQL
    username: postgres
    password: postgres # Coloque a senha real do seu PostgreSQL aqui
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Alterado para 'validate' para o Flyway gerenciar as migrations com segurança
    show-sql: true

# Ajustado para TRUE temporariamente para você conseguir usar o Swagger na porta 8081
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8081 # Note que a porta em modo prod passa a ser 8081

flyway:
  enabled: true
  baseline-on-migrate: true


